specVersion: 0.0.1
description: "Ternoa data indexer"
repository: ''
schema: ./schema.graphql
network:
  endpoint: "ws://127.0.0.1:9944"
  #endpoint: "wss://chaos.ternoa.com"
  types: {
    AccountDataOf: "AccountData",
    Address: "AccountId",
    CapsuleID: "u32",
    CapsuleIDOf: "NFTId",
    CapsuleData: {
      offchain_uri: "Vec<u8>",
      pk_hash: "Hash",
      creator: "AccountId",
      owner: "AccountId",
      locked: "bool"
    },
    NFTId: "u32",
    NFTIdOf: "NFTId",
    NFTData: {
      owner: "AccountId",
      details: "NFTDetails",
      sealed: "bool",
      locked: "bool",
      series_id: "NFTSeriesId"
    },
    NFTDetails: {
      offchain_uri: "Vec<u8>",
      series_id: "NFTSeriesId",
      is_capsule: "bool"
    },
    NFTSeriesDetails: {
      owner: 'AccountId',
      nfts: 'Vec<NFTId>'
    },
    NFTSeriesId: 'u32',
    LookupSource: "AccountId",
    "NFTCurrencyCombined": {
      "caps": "Balance",
      "tiime": "Balance"
    },
    "NFTCurrency": {
      "_enum": {
        "CAPS": "Balance",
        "TIIME": "Balance",
        "COMBINED": "NFTCurrencyCombined"
      }
    },
    "NFTCurrencyId": {
      "_enum": [
          "CAPS",
          "TIIME"
      ]
    }
  }

dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
