specVersion: 0.0.1
description: "Ternoa data indexer"
repository: ''
schema: ./schema.graphql
network:
  #endpoint: "ws://127.0.0.1:9944"
  endpoint: "wss://staging.chaos.ternoa.com"
  #endpoint: "wss://chaos.ternoa.com"
  #endpoint: "wss://testnet.ternoa.com"
  types: {
    "AccountDataOf": "AccountData",
    "Address": "MultiAddress",
    "LookupSource": "MultiAddress",
    "ShardIdentifier": "Hash",
    "Url": "Text",
    "URI": "Text",
    "ClusterId": "u32",
    "EnclaveId": "u32",
    "MarketplaceId": "u32",
    "BalanceCaps": "Balance",
    "NFTId": "u32",
    "String": "Text",
    "NFTSeriesId": "Text",
    "NFTData": {
        "owner": "AccountId",
        "ipfs_reference": "String",
        "series_id": "NFTSeriesId",
        "locked": "bool"
    },
    "NFTSeriesDetails": {
        "owner": "AccountId",
        "draft": "bool"
    },
    "NFTCurrencyCombined": {
        "caps": "Balance",
        "tiime": "Balance"
    },
    "NFTCurrency": {
        "_enum": {
            "Caps": "Balance",
            "Tiime": "Balance",
            "Combined": "NFTCurrencyCombined"
        }
    },
    "NFTCurrencyId": {
        "_enum": [
            "Caps",
            "Tiime"
        ]
    },
    "SaleInformation": {
        "account_id": "AccountId",
        "price": "NFTCurrency",
        "marketplace_id": "MarketplaceId"
    },
    "MarketplaceType": {
        "_enum": [
            "Public",
            "Private"
        ]
    },
    "MarketplaceInformation": {
        "kind": "MarketplaceType",
        "commission_fee": "u8",
        "owner": "AccountId",
        "allow_list": "Vec<AccountId>",
        "name": "String",
        "uri": "Option<URI>",
        "logo_uri": "Option<URI>"
    },
    "Cluster": {
        "enclaves": "Vec<EnclaveId>"
    },
    "Enclave": {
        "api_url": "Url"
    },
    "CapsuleData": {
        "owner": "AccountId",
        "ipfs_reference": "String"
    },
    "CapsuleLedger": "Vec<(NFTId, Balance)>",
    "Status": {
        "_enum": [
            "Free",
            "Reserved"
        ]
    },
    "Request": {
        "shard": "ShardIdentifier",
        "cyphertext": "Vec<u8>"
    }
  }

dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
