specVersion: 0.2.0
name: subql_ternoa
version: 1.0.0
description: Ternoa data indexer
repository: ""
schema:
  file: ./schema.graphql
network:
  genesisHash: "0x5097f5760dd0a37e4e048bfc18ce9ddf915a9e96a113ac46d99c2f17033ce81d"
  endpoint: wss://dev-0.ternoa.network/
  # dictionary: https://dictionary-alphanet.ternoa.dev/
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridge
            method: DepositMade

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nft
            method: NFTCreated
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nft
            method: NFTBurned
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nft
            method: NFTTransferred
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nft
            method: NFTDelegated
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nft
            method: NFTRoyaltySet
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nft
            method: CollectionCreated
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nft
            method: CollectionBurned
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nft
            method: CollectionClosed
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nft
            method: CollectionLimited
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nft
            method: NFTAddedToCollection

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: associatedAccounts
            method: UserAccountAdded
