specVersion: 0.2.0
name: subql_ternoa
version: 1.0.0
description: Ternoa data indexer
repository: ''
schema:
  file: ./schema.graphql
network:
  # genesisHash: '0xd44bcfb0e98da45ace37e4df8469e5dbba8c4fc5449acda24c50cea6f5f2ca99' #staging
  # endpoint: 'wss://staging.chaos.ternoa.com'
  # dictionary: 'https://dictionary-staging.ternoa.dev/'
  # genesisHash: '0xd9adfc7ea82be63ba28088d62b96e9270ad2af25c962afc393361909670835b2' #testnet
  # endpoint: 'wss://testnet.ternoa.com'
  # dictionary: 'https://dictionary-testnet.ternoa.dev/'
  genesisHash: '0x710016a91bfbd4ffc5035ae19b7b94be74a2fd2f693cc692aaedae35c0cacd58'
  endpoint: wss://dev.chaos.ternoa.com
  chaintypes:
    file: ./types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: associatedAccounts
            method: AltVRUsernameChanged
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: capsules
            method: CapsuleFundsAdded
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: capsules
            method: CapsuleIpfsReferenceChanged
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: capsules
            method: CapsuleRemoved
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: capsules
            method: CapsuleCreated
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: marketplace
            method: AccountAddedToAllowList
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: marketplace
            method: AccountAddedToDisallowList
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: marketplace
            method: AccountRemovedFromAllowList
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: marketplace
            method: AccountRemovedFromDisallowList
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: marketplace
            method: MarketplaceCreated
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: marketplace
            method: MarketplaceCommissionFeeChanged
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: marketplace
            method: MarketplaceDescriptionUpdated
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: marketplace
            method: MarketplaceLogoUriUpdated
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: marketplace
            method: MarketplaceTypeChanged
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: marketplace
            method: MarketplaceNameChanged
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: marketplace
            method: MarketplaceChangedOwner
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: marketplace
            method: MarketplaceUriUpdated
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: marketplace
            method: NftListed
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: marketplace
            method: NftSold
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nfts
            method: Burned
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nfts
            method: Created
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nfts
            method: SeriesFinished
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: nfts
            method: Transfer